name: otv-txt

on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install requests

      - name: Run otv
        run: python ${{ github.workspace }}/otv_py.py

      - name: commit-txt
        run: |
          git config --local user.email "f0rum@qq.com"
          git config --local user.name "happymem2023"
          git add .
          git commit *.txt -m "Add generated file"
          git push -f
